org.gradle.jvmargs=-Xmx6g -XX:MaxMetaspaceSize=1g -Dfile.encoding=UTF-8
org.gradle.java.home=C:/Users/eqbir/CodeProjects/Antigravity/gradle/jdk-17
org.gradle.caching=true
org.gradle.configuration-cache=true
org.gradle.parallel=true
kotlin.daemon.jvmargs=-Xmx3g
android.useAndroidX=true
android.nonTransitiveRClass=true
kotlin.code.style=official
